Repository jenkinsci/mercurial-plugin, pull requests merged in 2019-07, with the labels that each got.

#132 Code Improvements
  src/conf/checkstyle-ruleset.xml
  src/main/java/hudson/plugins/mercurial/Cache.java
  src/main/java/hudson/plugins/mercurial/HgExe.java
  src/main/java/hudson/plugins/mercurial/MercurialChangeLogParser.java
  src/main/java/hudson/plugins/mercurial/MercurialSCM.java
  src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
  src/main/java/hudson/plugins/mercurial/MercurialStatus.java
  src/main/java/hudson/plugins/mercurial/traits/MercurialBrowserSCMSourceTrait.java
  src/main/java/hudson/plugins/mercurial/traits/MercurialInstallationSCMSourceTrait.java
  src/main/resources/hudson/plugins/mercurial/MercurialSCM/buildEnv.groovy
  src/test/java/hudson/plugins/mercurial/CacheTest.java
  src/test/java/hudson/plugins/mercurial/ChangeComparatorTest.java
  src/test/java/hudson/plugins/mercurial/ConfigurationTest.java
  src/test/java/hudson/plugins/mercurial/CustomConfigTest.java
  src/test/java/hudson/plugins/mercurial/HgExeFunctionalTest.java
  src/test/java/hudson/plugins/mercurial/MatrixProjectTest.java
  src/test/java/hudson/plugins/mercurial/MercurialChangeLogParserTest.java
  src/test/java/hudson/plugins/mercurial/MercurialStatusTest.java
  src/test/java/hudson/plugins/mercurial/SCMTestBase.java
  src/test/java/hudson/plugins/mercurial/browser/HgBrowserSelectionTest.java
Labels: chore

#133 Do not rely on URL.equals in a test
  src/test/java/hudson/plugins/mercurial/browser/HgBrowserSelectionTest.java
Labels: test

#134 Switch to a BOM
  pom.xml
  src/test/java/hudson/plugins/mercurial/HgExeFunctionalTest.java
Labels: dependencies

#125 [JENKINS-55787] Switch labels from entry to checkbox
  src/main/resources/hudson/plugins/mercurial/MercurialInstallation/config.jelly
  src/main/resources/hudson/plugins/mercurial/MercurialSCM/config.jelly
Labels: enhancement
