Repository jenkinsci/mercurial-plugin, pull requests merged in 2020-04, with the labels that each got.

#135 BOM 3
  pom.xml
  src/test/java/hudson/plugins/mercurial/MercurialContainer.java
Labels: dependencies

#139 reuseForks=false
  pom.xml
Labels: chore

#138 Use JenkinsRule.waitOnline
  src/test/java/hudson/plugins/mercurial/MercurialContainer.java
Labels: chore

#137 Configure incrementals
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: chore

#141 Use GitHub as the source of documentation
  CHANGELOG.md
  README.md
  docs/images/mercurial.png
  pom.xml
Labels: documentation

#142 2.164.x
  pom.xml
Labels: dependencies

#143 Specify languages for README snippets
  README.md
Labels: documentation
