Repository jenkinsci/mercurial-plugin, pull requests merged in 2020-10, with the labels that each got.

#147 Using FlagRule
  pom.xml
  src/test/java/hudson/plugins/mercurial/MercurialSCMSource2Test.java
Labels: chore

#148 [JENKINS-62669] Removing Bitbucket support
  README.md
  src/main/java/hudson/plugins/mercurial/browser/BitBucket.java
  src/main/resources/hudson/plugins/mercurial/browser/BitBucket/config.jelly
  src/main/resources/hudson/plugins/mercurial/browser/BitBucket/help-url.html
  src/main/resources/index.jelly
  src/test/java/hudson/plugins/mercurial/browser/BitBucketTest.java
  src/test/java/hudson/plugins/mercurial/browser/HgBrowserSelectionTest.java
  src/test/resources/hudson/plugins/mercurial/browser/HgBrowserSelectionTest/browsersAvailableInDropDown.zip
  src/test/resources/hudson/plugins/mercurial/browser/HgBrowserSelectionTest/pickingUpAlternativeBrowser.zip
Labels: removed

#145 Add explicit license file to root of project
  LICENSE
Labels: documentation

#146 Add SCM-Manager repository browser
  src/main/java/hudson/plugins/mercurial/browser/ScmManager.java
  src/main/resources/hudson/plugins/mercurial/browser/ScmManager/config.jelly
  src/main/resources/hudson/plugins/mercurial/browser/ScmManager/help-url.html
  src/test/java/hudson/plugins/mercurial/browser/ScmManagerTest.java
Labels: enhancement

#149 [JENKINS-48867] A failure during branch indexing should be propagated so branches are not lost
  src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
  src/test/java/hudson/plugins/mercurial/MercurialSCMSource2Test.java
Labels: bug

#150 Running Mercurial 5.x in tests
  src/test/java/hudson/plugins/mercurial/FunctionalTest.java
  src/test/java/hudson/plugins/mercurial/MercurialContainer.java
  src/test/java/hudson/plugins/mercurial/MercurialSCMSource2Test.java
  src/test/java/hudson/plugins/mercurial/PipelineTest.java
  src/test/resources/hudson/plugins/mercurial/MercurialContainer/Dockerfile
Labels: test

#151 [JENKINS-46851] Need to pass credentials when looking up a commit
  src/main/java/hudson/plugins/mercurial/MercurialSCMSource.java
  src/test/java/hudson/plugins/mercurial/MercurialSCMSource2Test.java
Labels: bug

#152 Update Jenkins baseline & BOM, use MockAuthorizationStrategy
  pom.xml
  src/test/java/hudson/plugins/mercurial/ConfigurationTest.java
Labels: dependencies

#153 Enable Dependabot
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: chore
