Repository jenkinsci/mercurial-plugin, pull requests merged in 2021-11, with the labels that each got.

#183 No need to override `reuseForks`
  pom.xml
Labels: test

#184 Use vectorized icon
  src/main/java/hudson/plugins/mercurial/MercurialTagAction.java
  src/main/resources/hudson/plugins/mercurial/MercurialTagAction/summary.jelly
  src/main/webapp/images/16x16/logo.png
  src/main/webapp/images/24x24/logo.png
  src/main/webapp/images/32x32/logo.png
  src/main/webapp/images/48x48/logo.png
  src/main/webapp/images/logo.svg
Labels: enhancement

#185 [JENKINS-65175] Revert `ini4j` upgrade
  .github/dependabot.yml
  pom.xml
Labels: bug

#186 Fixing `MercurialRule.registerHook`
  src/test/java/hudson/plugins/mercurial/MercurialRule.java
Labels: test
